services:
    redis:
        image: redis:latest  # Use the latest Redis image from Docker Hub

    mongodb:
        image: mongo:latest  # Use the latest MongoDB image from Docker Hub
        volumes:
            - mongo-data:/data/db  # Mount volume for MongoDB data persistence

    zkwasmserver:
        image: zkwasm-server
        ports:
            - "8085:3000"
        environment:
            - URI=mongodb://mongodb:27017

volumes:
    mongo-data:  # Declare the volume for MongoDB
                                                                                                                    ~

