services:
    merkleservice:
        image: ghcr.io/delphinuslab/zkwasm-mini-rollup/zkwasm-merkleservice:latest # the zkwasm merkle db service from GitHub Container Registry
        command: ["./target/release/csm_service", "--uri", "/usr/rocksdb"]
        volumes:
            - rocks-data:/usr/rocksdb
        ports:
            - "3030:3030"  # Map service port
    redis:
        image: redis:latest  # Use the latest Redis image from Docker Hub
        ports:
            - "6379:6379"  # Map Redis port
          #  networks:
          #  - my-network

    mongodb:
        image: mongo:latest  # Use the latest MongoDB image from Docker Hub
        volumes:
            - mongo-data:/data/db  # Mount volume for MongoDB data persistence
          #  networks:
          #  - my-network
        ports:
            - "27017:27017"  # Map MongoDB port

volumes:
    mongo-data:  # Declare the volume for MongoDB
    rocks-data:  # Declare the volume for RocksDB

#networks:
#    my-network:
#        driver: bridge

