services:
    redis:
        image: redis:latest  # Use the latest Redis image from Docker Hub
        networks:
            - my-network

    mongodb:
        image: mongo:latest  # Use the latest MongoDB image from Docker Hub
        volumes:
            - mongo-data:/data/db  # Mount volume for MongoDB data persistence
        networks:
            - my-network

    zkwasmserver:
        image: zkwasm-server
        ports:
            - "8085:3000"
        environment:
            - URI=mongodb://mongodb:27017
        networks:
            - my-network

volumes:
    mongo-data:  # Declare the volume for MongoDB

networks:
    my-network:
        driver: bridge
