name: Build and Publish Merkle Service

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - 'Dockerfile.merkle'
      - '.github/workflows/build-merkle-image.yml'
      - 'dbservice/**'
  workflow_dispatch:  # Allow manual triggering

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/zkwasm-merkleservice

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Convert to lowercase
        id: lowercase
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}/zkwasm-merkleservice" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.merkle
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Generate image info
        if: success() && github.event_name != 'pull_request'
        run: |
          echo "Merkle service image built and pushed successfully"
          echo "Image: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}"
          echo "Tags: ${{ steps.meta.outputs.tags }}"

      - name: Notify build result
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Merkle service image built and pushed: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}"
          else
            echo "❌ Build failed: ${{ job.status }}"
          fi